//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TipsTravels_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inbox
    {
        public int MsgID { get; set; }
        public Nullable<int> PersonFromID { get; set; }
        public Nullable<int> PersonToID { get; set; }
        public Nullable<System.DateTime> DateOfMessage { get; set; }
        public string MsgContent { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
