//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TipsTravels_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostsStatu
    {
        public int PersonID { get; set; }
        public int PostsID { get; set; }
        public int Status { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Post Post { get; set; }
    }
}
