//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web;

namespace TipsTravels_System.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Post
    {
        public HttpPostedFileBase file { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.PostsStatus = new HashSet<PostsStatu>();
            this.Persons = new HashSet<Person>();
        }

        public int PostID { get; set; }
        public int PersonID { get; set; }
        public string TripTitle { get; set; }
        public string TripDetails { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<System.DateTime> TripDate { get; set; }
        public string TripDestination { get; set; }
        public byte[] TripImage { get; set; }
        public Nullable<decimal> TripPrice { get; set; }
        public Nullable<int> IsApproved { get; set; }

        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostsStatu> PostsStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> Persons { get; set; }
    }
}
